# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.1.0/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.1.0/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/pythonforios/git/PySmile

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/pythonforios/git/PySmile

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.1.0/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.1.0/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/pythonforios/git/PySmile/CMakeFiles /Users/pythonforios/git/PySmile/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/pythonforios/git/PySmile/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PySmile

# Build rule for target.
PySmile: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PySmile
.PHONY : PySmile

# fast build rule for target.
PySmile/fast:
	$(MAKE) -f CMakeFiles/PySmile.dir/build.make CMakeFiles/PySmile.dir/build
.PHONY : PySmile/fast

src/libsmile/block.o: src/libsmile/block.c.o
.PHONY : src/libsmile/block.o

# target to build an object file
src/libsmile/block.c.o:
	$(MAKE) -f CMakeFiles/PySmile.dir/build.make CMakeFiles/PySmile.dir/src/libsmile/block.c.o
.PHONY : src/libsmile/block.c.o

src/libsmile/block.i: src/libsmile/block.c.i
.PHONY : src/libsmile/block.i

# target to preprocess a source file
src/libsmile/block.c.i:
	$(MAKE) -f CMakeFiles/PySmile.dir/build.make CMakeFiles/PySmile.dir/src/libsmile/block.c.i
.PHONY : src/libsmile/block.c.i

src/libsmile/block.s: src/libsmile/block.c.s
.PHONY : src/libsmile/block.s

# target to generate assembly for a file
src/libsmile/block.c.s:
	$(MAKE) -f CMakeFiles/PySmile.dir/build.make CMakeFiles/PySmile.dir/src/libsmile/block.c.s
.PHONY : src/libsmile/block.c.s

src/libsmile/decode.o: src/libsmile/decode.c.o
.PHONY : src/libsmile/decode.o

# target to build an object file
src/libsmile/decode.c.o:
	$(MAKE) -f CMakeFiles/PySmile.dir/build.make CMakeFiles/PySmile.dir/src/libsmile/decode.c.o
.PHONY : src/libsmile/decode.c.o

src/libsmile/decode.i: src/libsmile/decode.c.i
.PHONY : src/libsmile/decode.i

# target to preprocess a source file
src/libsmile/decode.c.i:
	$(MAKE) -f CMakeFiles/PySmile.dir/build.make CMakeFiles/PySmile.dir/src/libsmile/decode.c.i
.PHONY : src/libsmile/decode.c.i

src/libsmile/decode.s: src/libsmile/decode.c.s
.PHONY : src/libsmile/decode.s

# target to generate assembly for a file
src/libsmile/decode.c.s:
	$(MAKE) -f CMakeFiles/PySmile.dir/build.make CMakeFiles/PySmile.dir/src/libsmile/decode.c.s
.PHONY : src/libsmile/decode.c.s

src/pysmile.o: src/pysmile.c.o
.PHONY : src/pysmile.o

# target to build an object file
src/pysmile.c.o:
	$(MAKE) -f CMakeFiles/PySmile.dir/build.make CMakeFiles/PySmile.dir/src/pysmile.c.o
.PHONY : src/pysmile.c.o

src/pysmile.i: src/pysmile.c.i
.PHONY : src/pysmile.i

# target to preprocess a source file
src/pysmile.c.i:
	$(MAKE) -f CMakeFiles/PySmile.dir/build.make CMakeFiles/PySmile.dir/src/pysmile.c.i
.PHONY : src/pysmile.c.i

src/pysmile.s: src/pysmile.c.s
.PHONY : src/pysmile.s

# target to generate assembly for a file
src/pysmile.c.s:
	$(MAKE) -f CMakeFiles/PySmile.dir/build.make CMakeFiles/PySmile.dir/src/pysmile.c.s
.PHONY : src/pysmile.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... PySmile"
	@echo "... src/libsmile/block.o"
	@echo "... src/libsmile/block.i"
	@echo "... src/libsmile/block.s"
	@echo "... src/libsmile/decode.o"
	@echo "... src/libsmile/decode.i"
	@echo "... src/libsmile/decode.s"
	@echo "... src/pysmile.o"
	@echo "... src/pysmile.i"
	@echo "... src/pysmile.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

